spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/modulo2db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  expiration-ms: 3600000
